### ISSUE TITLE
encountered panic trying to run API in mock mode

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/wiretap#61]
The panic was:

```
::1 - - [21/Nov/2023:14:39:49 +0000] "GET /ranch HTTP/1.1" 200 0 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9a42f7]

goroutine 4338 [running]:
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).Schema(0x0)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi@v0.13.11/datamodel/high/base/schema_proxy.go:77 +0x17
github.com/pb33f/libopenapi-validator/paths.comparePaths({0xc0016364c0?, 0x4, 0x1?}, {0xc001636380?, 0x4, 0x4}, {0xc0003ec138, 0x1, 0x4107c5?}, {0xc0024007a0, ...})
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.28/paths/paths.go:267 +0x37f
github.com/pb33f/libopenapi-validator/paths.FindPath(0xc002380a00, 0xc002292000)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.28/paths/paths.go:66 +0x5fb
github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpRequest(0xc000be4400, 0xc002380a00)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.28/validator.go:164 +0x4b
github.com/pb33f/wiretap/daemon.(*WiretapService).validateRequest(0xc001dc2d20, 0xc00174e300, 0xc0023688d0?)
        /home/runner/work/wiretap/wiretap/daemon/validate.go:52 +0x62
created by github.com/pb33f/wiretap/daemon.(*WiretapService).handleHttpRequest in goroutine 4336
        /home/runner/work/wiretap/wiretap/daemon/handle_request.go:160 +0xa6e
```

The command used:

`wiretap -s ./tests/specs/test_primary.yaml -x -b ./tests/specs -p 35123`

I can send you the spec we were using in DM on discord if you need it.

**Comment by n0rig** [comment]
@TristanSpeakEasy you are probably experiencing this issue: https://github.com/pb33f/wiretap/pull/53

I have not had the time recently to focus on this. Maybe next weekend.

**Comment by daveshanley** [comment]
This should be been resolved the latest update, the validator and libopenapi are current now.
