### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mknj** [pb33f/wiretap#71]
when playing with the tool i got this error after about 500 requests.
Unfortunately the tools does not tell me which request caused the issue.

```
INFO  wiretap is proxying all traffic to 'https://xxxxxxxxxxx'

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xa4ddca]

goroutine 11173 [running]:
github.com/pb33f/libopenapi-validator/requests.(*requestBodyValidator).ValidateRequestBody(0xc000da9d00, 0xc0004a7b00)
        /go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.34/requests/validate_body.go:32 +0x16a
github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpRequest.func2(0xc000f986c0?, 0x0?)
        /go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.34/validator.go:247 +0x30
created by github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpRequest in goroutine 11186
        /go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.34/validator.go:267 +0x346
```

**Comment by daveshanley** [comment]
Will fix this.

**Comment by pranayinos** [comment]
this is copy of https://github.com/pb33f/wiretap/issues/69 bug

**Comment by daveshanley** [comment]
Let me know if the latest wiretap still has this issue for you.
