### ISSUE TITLE
invalid memory address or nil pointer dereference in validator

### ISSUE THREAD

**Issue by spaced** [pb33f/wiretap#75]
tested with  `wiretap_0.0.50_linux_x86_64`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb7b641]

goroutine 299 [running]:
github.com/pb33f/libopenapi-validator/responses.(*responseBodyValidator).ValidateResponseBody(0xc00012cc00, 0xc000472000, 0xc000291680)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.37/responses/validate_body.go:51 +0x421
github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpResponse(0xc0002f4500, 0xc000309b80?, 0x0?)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.37/validator.go:116 +0xd3
github.com/pb33f/wiretap/daemon.(*WiretapService).validateResponse(0xc00032ab40, 0xc000544840, 0xc00026a138?)
        /home/runner/work/wiretap/wiretap/daemon/validate.go:19 +0x68
created by github.com/pb33f/wiretap/daemon.(*WiretapService).handleHttpRequest in goroutine 418
        /home/runner/work/wiretap/wiretap/daemon/handle_request.go:197 +0xdeb

```
response is e expected 400 error

**Comment by daveshanley** [comment]
This has been resolved in `v0.1.0`
