### ISSUE TITLE
Panic encountered making request 

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/wiretap#81]
This spec:

```yaml
openapi: 3.1.0
info:
  title: Test
  version: 0.1.0
paths:
  /anything/queryParams/deepObject/map:
    get:
      operationId: deepObjectQueryParamsMap
      parameters:
        - name: mapParam
          in: query
          style: deepObject
          schema:
            type: object
            additionalProperties:
              type: string
            example: { "test": "value", "test2": "value2" }
          required: true
        - name: mapArrParam
          in: query
          style: deepObject
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
            example: { "test": ["test", "test2"], "test2": ["test3", "test4"] }
      responses:
        "200":
          description: OK
```

Seems to cause the below panic:

```
2024/01/14 13:03:24 http: panic serving 127.0.0.1:40818: runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:1868 +0xb9
panic({0xce4100?, 0x1dbe3b0?})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
github.com/pb33f/wiretap/mock.(*ResponseMockEngine).ValidateSecurity(0x1?, 0xc0000d8500?, 0xc000054280?)
        /home/runner/work/wiretap/wiretap/mock/mock_engine.go:48 +0x24
github.com/pb33f/wiretap/mock.(*ResponseMockEngine).runWorkflow(0xc000400390, 0xc0000d8500)
        /home/runner/work/wiretap/wiretap/mock/mock_engine.go:226 +0x73
github.com/pb33f/wiretap/mock.(*ResponseMockEngine).GenerateResponse(...)
        /home/runner/work/wiretap/wiretap/mock/mock_engine.go:43
github.com/pb33f/wiretap/daemon.(*WiretapService).handleMockRequest(0xc0000caa90, 0xc0000344e0, 0xc000196600, 0xc0000d8b00)
        /home/runner/work/wiretap/wiretap/daemon/handle_mock.go:31 +0xb3
github.com/pb33f/wiretap/daemon.(*WiretapService).handleHttpRequest(0xc0000caa90, 0xc0000344e0)
        /home/runner/work/wiretap/wiretap/daemon/handle_request.go:172 +0x12ba
github.com/pb33f/wiretap/daemon.(*WiretapService).HandleHttpRequest(...)
        /home/runner/work/wiretap/wiretap/daemon/wiretap_service.go:99
github.com/pb33f/wiretap/cmd.handleHttpTraffic.func1.1({0x166f830?, 0xc0000c4230}, 0xc0000d8500)
        /home/runner/work/wiretap/wiretap/cmd/handle_http_traffic.go:27 +0xd5
net/http.HandlerFunc.ServeHTTP(0xc000101400?, {0x166f830?, 0xc0000c4230?}, 0xc000391a38?)
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0xc0000521f0?, {0x166f830, 0xc0000c4230}, 0xc0000d8500)
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2514 +0x142
github.com/pb33f/wiretap/cmd.handleHttpTraffic.func1.CompressHandler.CompressHandlerLevel.func3({0x16704d0, 0xc0004460e0}, 0xc0000d8500)
        /home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/compress.go:148 +0x69f
net/http.HandlerFunc.ServeHTTP(0x1e0c340?, {0x16704d0?, 0xc0004460e0?}, 0xc000391b50?)
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0xc000400f60?}, {0x16704d0?, 0xc0004460e0?}, 0x6?)
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0000f23f0, {0x1672020, 0xc0003803f0})
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 86
        /opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:3086 +0x5cb
```

when a request is made

**Comment by daveshanley** [comment]
This should be resolved in `v0.1.1`
