### ISSUE TITLE
panic in libopenapi when encountering json encoded path parameter

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/wiretap#92]
consider this spec:

```yaml
openapi: 3.1.0
info:
  title: Test
  version: 0.1.0
security:
  - apiKeyAuth: []
paths:
  /anything/pathParams/json/{jsonObj}:
    get:
      x-speakeasy-test: true
      operationId: pathParameterJson
      tags:
        - parameters
      parameters:
        - name: jsonObj
          in: path
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/simpleObject"
      responses:
        "200":
          content:
            application/json:
              schema:
                title: res
                type: object
                properties:
                  url:
                    type: string
                    example: 'http://localhost:35123/anything/pathParams/json/{"any":"any","bigint":8821239038968084,"bigintStr":"9223372036854775808","bool":true,"boolOpt":true,"date":"2020-01-01","dateTime":"2020-01-01T00:00:00.000001Z","decimal":3.141592653589793,"decimalStr":"3.14159265358979344719667586","enum":"one","float32":1.1,"int":1,"int32":1,"int32Enum":55,"intEnum":2,"num":1.1,"str":"test","strOpt":"testOptional"}'
                required:
                  - url
          description: OK
components:
  schemas:
    simpleObject:
      description: "A simple object that uses all our supported primitive types and enums and has optional properties."
      externalDocs:
        description: "A link to the external docs."
        url: "https://docs.speakeasyapi.dev"
      type: object
      properties:
        str:
          type: string
          description: "A string property."
          example: "test"
        bool:
          type: boolean
          description: "A boolean property."
          example: true
        int:
          type: integer
          description: "An integer property."
          example: 1
        int32:
          type: integer
          format: int32
          description: "An int32 property."
          example: 1
        num:
          type: number
          description: "A number property."
          example: 1.1
        float32:
          type: number
          format: float
          description: "A float32 property."
          example: 1.1
        enum:
          $ref: "#/components/schemas/enum"
        date:
          type: string
          format: date
          description: "A date property."
          example: "2020-01-01"
        dateTime:
          type: string
          format: date-time
          description: "A date-time property."
          example: "2020-01-01T00:00:00.000001Z"
        any:
          description: "An any property."
          example: "any"
        strOpt:
          type: string
          description: "An optional string property."
          example: "testOptional"
        boolOpt:
          type: boolean
          description: "An optional boolean property."
          example: true
        intOptNull:
          type: integer
          description: "An optional integer property will be null for tests."
        numOptNull:
          type: number
          description: "An optional number property will be null for tests."
        intEnum:
          type: integer
          description: "An integer enum property."
          enum:
            - 1
            - 2
            - 3
          example: 2
          x-speakeasy-enums:
            - First
            - Second
            - Third
        int32Enum:
          type: integer
          format: int32
          description: "An int32 enum property."
          enum:
            - 55
            - 69
            - 181
          example: 55
        bigint:
          type: integer
          format: bigint
          example: 8821239038968084
        bigintStr:
          type: string
          format: bigint
          example: "9223372036854775808"
        decimal:
          type: number
          format: decimal
          example: 3.141592653589793
        decimalStr:
          type: string
          format: decimal
          example: "3.14159265358979344719667586"
      required:
        - str
        - bool
        - int
        - int32
        - num
        - float32
        - enum
        - date
        - dateTime
        - any
        - intEnum
        - int32Enum
    enum:
      type: string
      description: "A string based enum"
      enum:
        - "one"
        - "two"
        - "three"
        - "four_and_more"
      example: "one"
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Authenticate using an API Key generated via our platform.
```

it causes this panic in libopenapi when a request is sent:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xabcfb7]

goroutine 359 [running]:
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).Schema(0x0)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi@v0.15.3/datamodel/high/base/schema_proxy.go:79 +0x17
github.com/pb33f/libopenapi-validator/parameters.(*paramValidator).ValidatePathParams(0x0?, 0xc00024e000)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.42/parameters/path_parameters.go:91 +0x452
github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpRequest.func1.2(0x0?, 0x0?, 0x0?)
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.42/validator.go:225 +0x27
created by github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpRequest.func1 in goroutine 356
        /home/runner/go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.42/validator.go:233 +0x3b2
```

**Comment by daveshanley** [comment]
in `v0.1.10` wiretap responds with this: 

```json
{
    "url": "http://localhost:35123/anything/pathParams/json/{\"any\":\"any\",\"bigint\":8821239038968084,\"bigintStr\":\"9223372036854775808\",\"bool\":true,\"boolOpt\":true,\"date\":\"2020-01-01\",\"dateTime\":\"2020-01-01T00:00:00.000001Z\",\"decimal\":3.141592653589793,\"decimalStr\":\"3.14159265358979344719667586\",\"enum\":\"one\",\"float32\":1.1,\"int\":1,\"int32\":1,\"int32Enum\":55,\"intEnum\":2,\"num\":1.1,\"str\":\"test\",\"strOpt\":\"testOptional\"}"
}
```
